bike/urls.py
from django.urls import path
from . import views


app_name='bike'

urlpatterns = [
    path("",views.index,name="index"),
    path("post/<str:slug>",views.detail,name="detail"),
    path("contact",views.contact_view,name="contact")
]

bike_booking/urls.py
from django.contrib import admin
from django.urls import path, include

handler404='bike_booking.views.custom_page_not_found'

urlpatterns = [
    path("",include("bike.urls")),
    path('admin/', admin.site.urls),
]

bike/models.py
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    

bike/forms.py
from django import forms

class Contactform(forms.Form):
    name = forms.CharField(label="Name", max_length=100,required=True)

    email = forms.EmailField(label="Email", required=True)

    message = forms.CharField(label="Message", required=True)

bike/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
import logging
from .models import Post
from django.http import Http404
from django.core.paginator import Paginator
from .forms import Contactform

# Static demo data
# posts = [
#         {'id':1, 'title':'post 1','content':'content of post 1'},
#         {'id':2, 'title':'post 2','content':'content of post 2'},
#         {'id':3, 'title':'post 3','content':'content of post 3'},
#         {'id':4, 'title':'post 4','content':'content of post 4'},
#     ]

def index(request):
    bikes_title="Lates Bikes"

    #get data from post models
    all_posts = Post.objects.all()

    paginator = Paginator(all_posts,5)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    return render(request,'index.html',{'heading_bike':bikes_title, 'page_obj':page_object})

def detail(request,slug):
    try:
        post=Post.objects.get(slug=slug)
        related_post=Post.objects.filter(category = post.category).exclude(pk=post.id)

    except Post.DoesNotExist:
        raise Http404("Post does not Exists")
    # post = next((item for item in posts if item['id']==int(post_id)),None)
    # logger = logging.getLogger("TESTING")
    # logger.debug(f'Post variable is {post}')
    return render(request,'detail.html',{'post': post, 'related_post':related_post})

def contact_view(request):
    if request.method == 'Post':
        form = Contactform(request.POST)
        logger = logging.getLogger("TESTING")
        if form.is_valid():
            logger.debug(f'Post Data is {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}')
        else:
            logger.debug("Form Validation Failure")
    return render(request,'contact.html')

bike_booking/views.py
from django.shortcuts import render


def custom_page_not_found(request, exception):
    return render(request,'404.html',status=404)

bike/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bike/style.css' %}">
<body >

    <!-- Header Files -->
    {% include 'includes/header.html' %}

    <!-- Dynamic Content -->
     {% block content %}
     {% endblock %}

     <!-- Footer File -->
      {% include 'includes/footer.html' %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

bike/templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>
                <form method="post" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" >
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" >
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" ></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}   

bike/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}}<small style="font-size:18px">({{post.category.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at|date:"F j, Y"}}</p>
              <p>{{post.content}}</p>
              <img src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
              
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_post%}
                    <li><a href="{% url 'bike:detail' slug=related_post.slug%}">{{related_post.title}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
  {% endblock %}

bike/templates/includes/footer.html
    <footer class="bg-dark text-light p-3 fixed-bottom">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
    </footer>

bike/templates/includes/header.html
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
               <a class="text-decoration-none text-light" href="/"><h3>Bike Booking</h3></a> 
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="/">Home</a>
                    <a class="text-light text-decoration-none" href="/about">About</a>
                    <a class="text-light text-decoration-none" href="/contact">Contact</a>
                </div>
            </div>
        </div>
    </header>

bike/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >{{heading_bike | upper}}</h2>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div>
            </div>
        </div>
        <div class="row m-3">
            {% if page_obj %}
            {% for post in page_obj%}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img class="post-img" src="{{post.img_url}}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content|truncatechars:50}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url 'bike:detail' slug=post.slug%}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
            <div class="col-12 my-3">
                {% if page_obj.has_other_pages %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {% if page_obj.has_previous%}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo; first</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">previous</span>
                                </a>
                            </li>
                            {%endif%}

                            <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                            {%if page_obj.has_next%}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">next</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                    <span aria-hidden="true">last &raquo;</span>
                                </a>
                            </li>
                            {%endif%}
                        </ul>
                    </nav>
                {%endif%}
            </div>
            {%else%}
                <p>No Post Available Right Now</p>
            {%endif%}
        </div>
        <div class="row">
           
        </div>
        
    </div>
{% endblock %}